onboarding = false
[ui]
agent_panel_sort = "priority"
[keys]
prefix="ctrl+s"
copy_mode = "prefix+v"
split_vertical = "prefix+|"
navigate_workspace_down = "j"
navigate_workspace_up = "k"
last_pane = 'prefix+Space'
[ui.toast]
delivery = "terminal"
delay_seconds = 1
[ui.toast.herdr]
position = "bottom-right"
[theme]
name = "one-light"
