git:
  nerdFontsVersion: "3"
  pagers:
    - colorArg: always
      pager: delta --paging=never --syntax-theme=GitHub
      #pager: delta --paging=never --true-color=auto --dark --side-by-side --line-numbers --syntax-theme=Dracula --width=variable --navigate
customCommands:
  - key: "c"
    context: "global"
    command: "git commit -v"
    description: "Commit changes using git editor"
    output: terminal
